// Code generated by protoc-gen-go. DO NOT EDIT.
// source: micro.proto

package micro

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type FooResponse_Corpus int32

const (
	FooResponse_UNIVERSAL FooResponse_Corpus = 0
	FooResponse_WEB       FooResponse_Corpus = 1
	FooResponse_IMAGES    FooResponse_Corpus = 2
	FooResponse_LOCAL     FooResponse_Corpus = 3
	FooResponse_NEWS      FooResponse_Corpus = 4
	FooResponse_PRODUCTS  FooResponse_Corpus = 5
	FooResponse_VIDEO     FooResponse_Corpus = 6
)

var FooResponse_Corpus_name = map[int32]string{
	0: "UNIVERSAL",
	1: "WEB",
	2: "IMAGES",
	3: "LOCAL",
	4: "NEWS",
	5: "PRODUCTS",
	6: "VIDEO",
}

var FooResponse_Corpus_value = map[string]int32{
	"UNIVERSAL": 0,
	"WEB":       1,
	"IMAGES":    2,
	"LOCAL":     3,
	"NEWS":      4,
	"PRODUCTS":  5,
	"VIDEO":     6,
}

func (x FooResponse_Corpus) String() string {
	return proto.EnumName(FooResponse_Corpus_name, int32(x))
}

func (FooResponse_Corpus) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_0147923bbc6a29d9, []int{1, 0}
}

type FooRequest struct {
	Foo                  int32                     `protobuf:"varint,1,opt,name=foo,proto3" json:"foo,omitempty"`
	Bar                  []string                  `protobuf:"bytes,2,rep,name=bar,proto3" json:"bar,omitempty"`
	Map                  *FooRequest_MapFieldEntry `protobuf:"bytes,3,opt,name=map,proto3" json:"map,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                  `json:"-"`
	XXX_unrecognized     []byte                    `json:"-"`
	XXX_sizecache        int32                     `json:"-"`
}

func (m *FooRequest) Reset()         { *m = FooRequest{} }
func (m *FooRequest) String() string { return proto.CompactTextString(m) }
func (*FooRequest) ProtoMessage()    {}
func (*FooRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0147923bbc6a29d9, []int{0}
}

func (m *FooRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooRequest.Unmarshal(m, b)
}
func (m *FooRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooRequest.Marshal(b, m, deterministic)
}
func (m *FooRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooRequest.Merge(m, src)
}
func (m *FooRequest) XXX_Size() int {
	return xxx_messageInfo_FooRequest.Size(m)
}
func (m *FooRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_FooRequest.DiscardUnknown(m)
}

var xxx_messageInfo_FooRequest proto.InternalMessageInfo

func (m *FooRequest) GetFoo() int32 {
	if m != nil {
		return m.Foo
	}
	return 0
}

func (m *FooRequest) GetBar() []string {
	if m != nil {
		return m.Bar
	}
	return nil
}

func (m *FooRequest) GetMap() *FooRequest_MapFieldEntry {
	if m != nil {
		return m.Map
	}
	return nil
}

type FooRequest_MapFieldEntry struct {
	Key                  int32    `protobuf:"varint,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                string   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FooRequest_MapFieldEntry) Reset()         { *m = FooRequest_MapFieldEntry{} }
func (m *FooRequest_MapFieldEntry) String() string { return proto.CompactTextString(m) }
func (*FooRequest_MapFieldEntry) ProtoMessage()    {}
func (*FooRequest_MapFieldEntry) Descriptor() ([]byte, []int) {
	return fileDescriptor_0147923bbc6a29d9, []int{0, 0}
}

func (m *FooRequest_MapFieldEntry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooRequest_MapFieldEntry.Unmarshal(m, b)
}
func (m *FooRequest_MapFieldEntry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooRequest_MapFieldEntry.Marshal(b, m, deterministic)
}
func (m *FooRequest_MapFieldEntry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooRequest_MapFieldEntry.Merge(m, src)
}
func (m *FooRequest_MapFieldEntry) XXX_Size() int {
	return xxx_messageInfo_FooRequest_MapFieldEntry.Size(m)
}
func (m *FooRequest_MapFieldEntry) XXX_DiscardUnknown() {
	xxx_messageInfo_FooRequest_MapFieldEntry.DiscardUnknown(m)
}

var xxx_messageInfo_FooRequest_MapFieldEntry proto.InternalMessageInfo

func (m *FooRequest_MapFieldEntry) GetKey() int32 {
	if m != nil {
		return m.Key
	}
	return 0
}

func (m *FooRequest_MapFieldEntry) GetValue() string {
	if m != nil {
		return m.Value
	}
	return ""
}

type FooResponse struct {
	ResFoo               int32              `protobuf:"varint,1,opt,name=resFoo,proto3" json:"resFoo,omitempty"`
	ResBar               []string           `protobuf:"bytes,2,rep,name=resBar,proto3" json:"resBar,omitempty"`
	Req                  *FooRequest        `protobuf:"bytes,3,opt,name=req,proto3" json:"req,omitempty"`
	Corp                 FooResponse_Corpus `protobuf:"varint,4,opt,name=corp,proto3,enum=micro.FooResponse_Corpus" json:"corp,omitempty"`
	XXX_NoUnkeyedLiteral struct{}           `json:"-"`
	XXX_unrecognized     []byte             `json:"-"`
	XXX_sizecache        int32              `json:"-"`
}

func (m *FooResponse) Reset()         { *m = FooResponse{} }
func (m *FooResponse) String() string { return proto.CompactTextString(m) }
func (*FooResponse) ProtoMessage()    {}
func (*FooResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0147923bbc6a29d9, []int{1}
}

func (m *FooResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FooResponse.Unmarshal(m, b)
}
func (m *FooResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FooResponse.Marshal(b, m, deterministic)
}
func (m *FooResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FooResponse.Merge(m, src)
}
func (m *FooResponse) XXX_Size() int {
	return xxx_messageInfo_FooResponse.Size(m)
}
func (m *FooResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_FooResponse.DiscardUnknown(m)
}

var xxx_messageInfo_FooResponse proto.InternalMessageInfo

func (m *FooResponse) GetResFoo() int32 {
	if m != nil {
		return m.ResFoo
	}
	return 0
}

func (m *FooResponse) GetResBar() []string {
	if m != nil {
		return m.ResBar
	}
	return nil
}

func (m *FooResponse) GetReq() *FooRequest {
	if m != nil {
		return m.Req
	}
	return nil
}

func (m *FooResponse) GetCorp() FooResponse_Corpus {
	if m != nil {
		return m.Corp
	}
	return FooResponse_UNIVERSAL
}

func init() {
	proto.RegisterEnum("micro.FooResponse_Corpus", FooResponse_Corpus_name, FooResponse_Corpus_value)
	proto.RegisterType((*FooRequest)(nil), "micro.FooRequest")
	proto.RegisterType((*FooRequest_MapFieldEntry)(nil), "micro.FooRequest.MapFieldEntry")
	proto.RegisterType((*FooResponse)(nil), "micro.FooResponse")
}

func init() { proto.RegisterFile("micro.proto", fileDescriptor_0147923bbc6a29d9) }

var fileDescriptor_0147923bbc6a29d9 = []byte{
	// 358 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x8c, 0x92, 0xcb, 0x4e, 0xdb, 0x40,
	0x18, 0x85, 0x3b, 0x19, 0xdb, 0x8d, 0xff, 0x34, 0xd5, 0xf4, 0x57, 0x55, 0xb9, 0xd9, 0xd4, 0x4a,
	0x37, 0xde, 0x60, 0x20, 0x2c, 0x58, 0xe7, 0x62, 0xa3, 0x48, 0xb9, 0xa0, 0x71, 0x2e, 0x12, 0x3b,
	0xc7, 0x0c, 0x22, 0xca, 0x65, 0x9c, 0x71, 0x12, 0x29, 0x6f, 0xc1, 0x03, 0xf0, 0x8a, 0xbc, 0x03,
	0xf2, 0x85, 0x00, 0xca, 0x86, 0xdd, 0x7f, 0xce, 0x1c, 0x9d, 0xf3, 0x2d, 0x06, 0x2a, 0xab, 0x79,
	0xa4, 0xa4, 0x1b, 0x2b, 0xb9, 0x95, 0xa8, 0x67, 0xa2, 0xfe, 0x4c, 0x00, 0x7c, 0x29, 0xb9, 0xd8,
	0xec, 0x44, 0xb2, 0x45, 0x06, 0xf4, 0x41, 0x4a, 0x8b, 0xd8, 0xc4, 0xd1, 0x79, 0x7a, 0xa6, 0xce,
	0x2c, 0x54, 0x56, 0xc9, 0xa6, 0x8e, 0xc9, 0xd3, 0x13, 0x2f, 0x81, 0xae, 0xc2, 0xd8, 0xa2, 0x36,
	0x71, 0x2a, 0x8d, 0x7f, 0x6e, 0x5e, 0xfa, 0xde, 0xe1, 0xf6, 0xc3, 0xd8, 0x9f, 0x8b, 0xe5, 0xbd,
	0xb7, 0xde, 0xaa, 0x03, 0x4f, 0xb3, 0xb5, 0x6b, 0xa8, 0x7e, 0x72, 0xd3, 0xd6, 0x85, 0x38, 0xbc,
	0xed, 0x2c, 0xc4, 0x01, 0x7f, 0x83, 0xbe, 0x0f, 0x97, 0x3b, 0x61, 0x95, 0x6c, 0xe2, 0x98, 0x3c,
	0x17, 0xf5, 0x17, 0x02, 0x95, 0xac, 0x3a, 0x89, 0xe5, 0x3a, 0x11, 0xf8, 0x07, 0x0c, 0x25, 0x12,
	0xff, 0x88, 0x58, 0xa8, 0xc2, 0x6f, 0x1d, 0x41, 0x0b, 0x85, 0xff, 0x81, 0x2a, 0xb1, 0x29, 0x58,
	0x7f, 0x9d, 0xb0, 0xf2, 0xf4, 0x15, 0xcf, 0x40, 0x8b, 0xa4, 0x8a, 0x2d, 0xcd, 0x26, 0xce, 0xcf,
	0xc6, 0xdf, 0x8f, 0xa9, 0x7c, 0xd6, 0x6d, 0x4b, 0x15, 0xef, 0x12, 0x9e, 0xc5, 0xea, 0x77, 0x60,
	0xe4, 0x1a, 0xab, 0x60, 0x8e, 0x07, 0xdd, 0x89, 0xc7, 0x83, 0x66, 0x8f, 0x7d, 0xc3, 0xef, 0x40,
	0xa7, 0x5e, 0x8b, 0x11, 0x04, 0x30, 0xba, 0xfd, 0xe6, 0x8d, 0x17, 0xb0, 0x12, 0x9a, 0xa0, 0xf7,
	0x86, 0xed, 0x66, 0x8f, 0x51, 0x2c, 0x83, 0x36, 0xf0, 0xa6, 0x01, 0xd3, 0xf0, 0x07, 0x94, 0x6f,
	0xf9, 0xb0, 0x33, 0x6e, 0x8f, 0x02, 0xa6, 0xa7, 0x91, 0x49, 0xb7, 0xe3, 0x0d, 0x99, 0xd1, 0x50,
	0x50, 0x0d, 0x44, 0xa8, 0xa2, 0xc7, 0x40, 0xa8, 0xfd, 0x3c, 0x12, 0x78, 0x0e, 0x46, 0x6e, 0xe0,
	0x29, 0x7d, 0x0d, 0x4f, 0x51, 0xf1, 0x02, 0xf4, 0x91, 0xf4, 0x95, 0xfc, 0x62, 0xde, 0x21, 0x2d,
	0xfa, 0x44, 0xc8, 0xcc, 0xc8, 0x7e, 0xc5, 0xd5, 0x6b, 0x00, 0x00, 0x00, 0xff, 0xff, 0x12, 0x2c,
	0x93, 0x23, 0x24, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// SearchServiceClient is the client API for SearchService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type SearchServiceClient interface {
	Search(ctx context.Context, in *FooRequest, opts ...grpc.CallOption) (*FooResponse, error)
	ToFro(ctx context.Context, opts ...grpc.CallOption) (SearchService_ToFroClient, error)
}

type searchServiceClient struct {
	cc *grpc.ClientConn
}

func NewSearchServiceClient(cc *grpc.ClientConn) SearchServiceClient {
	return &searchServiceClient{cc}
}

func (c *searchServiceClient) Search(ctx context.Context, in *FooRequest, opts ...grpc.CallOption) (*FooResponse, error) {
	out := new(FooResponse)
	err := c.cc.Invoke(ctx, "/micro.SearchService/Search", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *searchServiceClient) ToFro(ctx context.Context, opts ...grpc.CallOption) (SearchService_ToFroClient, error) {
	stream, err := c.cc.NewStream(ctx, &_SearchService_serviceDesc.Streams[0], "/micro.SearchService/ToFro", opts...)
	if err != nil {
		return nil, err
	}
	x := &searchServiceToFroClient{stream}
	return x, nil
}

type SearchService_ToFroClient interface {
	Send(*FooRequest) error
	CloseAndRecv() (*FooResponse, error)
	grpc.ClientStream
}

type searchServiceToFroClient struct {
	grpc.ClientStream
}

func (x *searchServiceToFroClient) Send(m *FooRequest) error {
	return x.ClientStream.SendMsg(m)
}

func (x *searchServiceToFroClient) CloseAndRecv() (*FooResponse, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(FooResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// SearchServiceServer is the server API for SearchService service.
type SearchServiceServer interface {
	Search(context.Context, *FooRequest) (*FooResponse, error)
	ToFro(SearchService_ToFroServer) error
}

func RegisterSearchServiceServer(s *grpc.Server, srv SearchServiceServer) {
	s.RegisterService(&_SearchService_serviceDesc, srv)
}

func _SearchService_Search_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FooRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SearchServiceServer).Search(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/micro.SearchService/Search",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SearchServiceServer).Search(ctx, req.(*FooRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SearchService_ToFro_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SearchServiceServer).ToFro(&searchServiceToFroServer{stream})
}

type SearchService_ToFroServer interface {
	SendAndClose(*FooResponse) error
	Recv() (*FooRequest, error)
	grpc.ServerStream
}

type searchServiceToFroServer struct {
	grpc.ServerStream
}

func (x *searchServiceToFroServer) SendAndClose(m *FooResponse) error {
	return x.ServerStream.SendMsg(m)
}

func (x *searchServiceToFroServer) Recv() (*FooRequest, error) {
	m := new(FooRequest)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _SearchService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "micro.SearchService",
	HandlerType: (*SearchServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Search",
			Handler:    _SearchService_Search_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ToFro",
			Handler:       _SearchService_ToFro_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "micro.proto",
}
